name: baseball_env
channels:
  - defaults
dependencies:
  - build
  - numpy
  - pylint
  - python=3
  - plotly
  - dash
  - pandas
  - scipy
  - pip:
    - itertools
    - python_tsp==0.4.1
    - contourpy==1.0.6
    - numpy==1.26.4
    - dash-bootstrap-components==1.5.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-loading-spinners==1.0.3
    - dash-table==5.0.0